# Aquest fitxer és la configuració principal del projecte Flutter.
# Serveix per definir l’entorn de treball, les llibreries que necessita l’aplicació,
# les eines de desenvolupament i els recursos visuals o fitxers que s’han d’incloure al projecte.

name: cims
description: Frontend multiplataforma de CiMS per consultar cims, registrar ascensions i gestionar el progrés de l'usuari.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  auto_route: ^11.1.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  flutter_secure_storage: ^10.0.0
  google_maps_flutter: ^2.14.2
  collection: ^1.19.1
  image_picker: ^1.2.2
  image_picker_for_web: ^3.1.1
  flutter_image_compress: ^2.4.0
  material_symbols_icons: ^4.2928.1
  geolocator: ^14.0.2
  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.5.0
  build_runner: ^2.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/cims_logo.svg
    - assets/images/montana_0001.png