USE cims_db;

INSERT INTO regions (name) VALUES
('Alt Camp'),
('Alt Empordà'),
('Alt Penedès'),
('Alt Urgell'),
('Alta Ribagorça'),
('Anoia'),
('Aran'),
('Bages'),
('Baix Camp'),
('Baix Ebre'),
('Baix Empordà'),
('Baix Llobregat'),
('Baix Penedès'),
('Barcelonès'),
('Berguedà'),
('Cerdanya'),
('Conca de Barberà'),
('Garraf'),
('Garrigues'),
('Garrotxa'),
('Gironès'),
('Lluçanès'),
('Maresme'),
('Moianès'),
('Montsià'),
('Noguera'),
('Osona'),
('Pallars Jussà'),
('Pallars Sobirà'),
("Pla d'Urgell"),
("Pla de l'Estany"),
('Priorat'),
("Ribera d'Ebre"),
('Ripollès'),
('Segarra'),
('Segrià'),
('Selva'),
('Solsonès'),
('Tarragonès'),
('Terra Alta'),
('Urgell'),
('Vallès Occidental'),
('Vallès Oriental');