steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cims/cims-backend:$COMMIT_SHA'
      - './backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cims/cims-backend:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cims-backend'
      - '--image'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cims/cims-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-southwest1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'cims-backend@project-b3d3b0b0-7c7e-40b5-9a1.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - 'insproject-b3d3b0b0-7c7e-40b5-9a1:europe-southwest1:cims-26'
      - '--set-env-vars'
      - 'NODE_ENV=production,INSTANCE_CONNECTION_NAME=insproject-b3d3b0b0-7c7e-40b5-9a1:europe-southwest1:cims-26'
      - '--set-secrets'
      - 'DB_NAME=DB_NAME:latest,DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,JWT_SECRET=JWT_SECRET:latest,FRONTEND_URL=FRONTEND_URL:latest'

images:
  - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cims/cims-backend:$COMMIT_SHA'