steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cims/cims-backend:$COMMIT_SHA'
      - './backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cims/cims-backend:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cims-backend'
      - '--image'
      - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cims/cims-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-southwest1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'cims-backend@project-b3d3b0b0-7c7e-40b5-9a1.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - 'project-b3d3b0b0-7c7e-40b5-9a1:europe-southwest1:cims-26'
      - '--set-env-vars'
      - 'NODE_ENV=production,INSTANCE_CONNECTION_NAME=project-b3d3b0b0-7c7e-40b5-9a1:europe-southwest1:cims-26'
      - '--set-secrets'
      - 'DB_NAME=DB_NAME:latest,
        DB_USER=DB_USER:latest,
        DB_PASSWORD=DB_PASSWORD:latest,
        JWT_SECRET=JWT_SECRET:latest,
        FRONTEND_URL=FRONTEND_URL:latest,
        MAIL_FROM=MAIL_FROM:latest,
        APP_URL=APP_URL:latest,
        SENDGRID_API_KEY=SENDGRID_API_KEY:latest,
        CORS_DEV_ORIGINS=CORS_DEV_ORIGINS:latest,
        GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest,

images:
  - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cims/cims-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY